# Generated by Django 4.2.2 on 2023-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
    ]
