# Generated by Django 4.2.2 on 2023-10-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_winner_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
